### PR TITLE
Fix #48 - confusion with timestamps resolved

### LINKED ISSUE #48: Cannot update or change .bib file
I am using Atom 1.2.3 and autocomplete-bibtex 6.1. I am trying to update my .bib file, but new entries are not reflected in the autocomplete when I type. I have tried restarting Atom, no luck. I have even disabled/uninstalled autocomplete-bibtex 6.1 and still new entries are not reflected. Now, I find that I cannot even change the .bib file to something else: the entries in my original .bib file are the ones reflected in the autocomplete, even though I have changed the setting to a new .bib file.

I suspect this is some error with updating/deleting a temp file database? Where is the default location for this database?

### PR DESCRIPTION
**Pull request by maecky**
Fixes issue #48

### CODE REVIEW

**Comment by apcshields** [comment]
@maecky,

Thank you! Figuring out what we were doing with datetimes and serialize has been on my list of things to do.

I'll see what I can do about resolving the merge conflicts and merging this over the weekend.

Thanks,
Andrew

**Comment by maecky** [comment]
@apcshields ,
No problem, I am glad if I can give back to the open source community.

There shouldn't be any merge conflicts for tag v0.6.1 (which is also the recent version number of the package in atom) - but I could only create a pull request to the master branch.

Is there any reason, why the head of the repository doesn't correspond with the installed package in atom?

Kind Regars,
Maecky

**Comment by apcshields** [comment]
:sigh: In short, because I was sloppy, and then because I haven't had time to clean up the way I should.

**Comment by maecky** [comment]
Ok, I just wasn't sure if I made a mistake on creating the pull request ;)

**Comment by apcshields** [comment]
Closed by 65813fb5328a2221eed7122b1c9d50209df45105.

**Comment by apcshields** [comment]
@maecky,

I merged this and #47 into the newly-created `stable` branch and released your fixes as [v0.6.2](https://github.com/apcshields/autocomplete-bibtex/releases/tag/v0.6.2).

Thanks for your help!
Andrew

**Pull request closed without merging**
