### PR TITLE
#24 Add search UI

### PR DESCRIPTION
**Pull request by mangecoeur**
Addresses #24 - adds a simple model to allow searching through bibliography, hit enter to insert citekey. Adds corresponding command, and also a command to force reload your bib file

### CODE REVIEW

**Comment by tpoisot** [comment]
I really like the idea -- but we just added support for citeproc json and yaml files in addition to bibtex, so you'll need to rebase.

**Comment by mangecoeur** [comment]
ok will do

**Comment by tpoisot** [comment]
:+1: -- Your Citer package was one of the things that made it hard to leave SublimeText behind, by the way.

**Comment by apcshields** [comment]
@mangecoeur It doesn't look like you've rebased and updated the pull request. Are you ready to do that?

Thanks!

**Comment by mangecoeur** [comment]
So I did the rebase for the search view, along with some cosmetic changes. I did see some issues with styles that should have been inherited from SelectListView but weren't but I wasn't able to work around that, it could be a problem only on my end though so please have a look and see...

**Comment by mangecoeur** [comment]
P.s. let me know if you are ready to merge the PR

**Comment by apcshields** [comment]
@mangecoeur,




I'm hoping to make some time to work on it tomorrow. Is that ok?




Andrew



—

**Comment by mangecoeur** [comment]
Sure no problem

**Pull request merged**
